name: test-suite

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Test PHP 8.4
        run: make test PHP=8.4
      - name: Test PHP 8.3
        run: make test PHP=8.3
      - name: Test PHP 8.2
        run: make test PHP=8.2
      - name: Test PHP 8.1
        run: make test PHP=8.1
      - uses: codecov/codecov-action@v6
        with:
          directory: build
